---
title: "Disaster Relief Simulation"
author: "Daniel Dittenhafer & Jashan Narham"
date: "April 26, 2016"
documentclass: article 
geometry: margin=0.75in
output: 
  pdf_document:
    number_sections: yes
subtitle: "DATA 604: Simulation & Modeling"
---

# Abstract

# Keywords

# Literature Review

# Methodology

## Structure

### Supplier

A Supplier entity is included in the simulation model. This entity is the *Source* of Relief Supplies. This entity is used, through design of experiements, to simulate both reliable partner suppliers as well as adhoc suppliers (more variability in their supply). The following variables (Referenced Properties) were created to facilitate the study: 

* The time to deliver a shipment of supplies:  *SupplierTravelTimeToWarehouse*. 

* The maximum number of relief supplies which the supplier will provide: *SupplierMaximumArrivals* 

The delivery vehicle, *PartnerVehicle*, was set to require a full load prior to departing for the Warehouse.

* The capacity of the *PartnerVehicle*: *SupplierVehicleCapacity*

### Warehouse

A Warehouse was added to store disaster relief supplies in preparation for a disaster. This entity was modeled as a *Server* which processes incoming **Relief Supplies** and stores them in a ready state for movement to Distribution Site.

The following variables were created to facilitate design of experiments:

* The storage capacity of the warehouse: *WarehouseStorageCapacity*

The delivery vehicle, *WarehouseVehicle*, was set to require a full load prior to departing for a distribution site and have period failures.

* The capacity of the *WarehouseVehicle*: *WarehouseVehicleCapacity*

* The frequency of failure: *WarehouseVehicleUptimeBetweenFailures*

Selection Weight on the Paths from the Warehouse to the Distribution Sites was set to dynamically adjust based on the number of Relief Beneficiaries  waiting for Relief Supplies.

### Distribution Sites

Two distribution sites were included in the model. 

The following variables were created to facilitate design of experiments:

* The processing time needed to provide a *ReliefSupply* item to a *ReliefBeneficiary*: DistSiteProcessingTime

### Relief Beneficiaries

The Relief Beneficiaries represent entities who are affected by the disaster and require *ReliefSupplies*. Two separate *Sources* were included in the model to simulate separate origination points beneficiaries for to each distribution site.

* *ReliefBeneficiaryInterarrivalTime*

* *DisasterVictimMaximumArrivals*

### Disaster

The "Disaster" is set to begin at a designated time into the simulation. This gives some time to prime the pump and prestage relief supplies through the warehouse.

The following variables were created to facilitate design of experiments:

* The amount of time between simulation start and onset of the disaster: *DisasterTimeOffset*


**TBD** We may need to adjust this... 

## Design of Experiments



# Results



# Summary

# Appendix: Raw Code

